apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mydb
  name: mysqldb
  namespace: default
  resourceVersion: "1621123"
  uid: f6c92cc8-24cd-41cf-b05d-9ffc7ae290d0
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: <password_you_want_to_set>
    - name: MYSQL_DATABASE
      value: wpdb
    - name: MYSQL_USER
      value: piyush
    - name: MYSQL_PASSWORD
      value: <password_you_want_to_set>
    image: mysql:5.7
    imagePullPolicy: IfNotPresent
    name: mydb
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mrcpg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-31-42-165.ap-south-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-mrcpg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-05T10:15:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-09-05T10:15:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-09-05T10:15:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-09-05T10:15:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f9df2d854619fa8734c9d9b5b3e8a765da7f4021dfb79252fbb258b4c17f9ead
    image: mysql:5.7
    imageID: docker-pullable://mysql@sha256:7cf2e7d7ff876f93c8601406a5aa17484e6623875e64e7acc71432ad8e0a3d7e
    lastState: {}
    name: mydb
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-09-05T10:15:19Z"
  hostIP: 172.31.42.165
  phase: Running
  podIP: 10.244.1.14
  podIPs:
  - ip: 10.244.1.14
  qosClass: BestEffort
  startTime: "2021-09-05T10:15:18Z"
